name: Demo workflow

on:
  - push
  - workflow_dispatch

jobs:
  display-vars:
    runs-on: ubuntu-latest
    steps:
      - name: print vars
        run: echo "${{ toJson(vars) }}"
      - name: print env
        run: echo "${{ env.ENV_DESC }}"
